
all:		
	g++ world.cpp obstacle.cpp support_methods.cpp path_duplication_check.cpp tunnel_optimization.cpp support_methods.h path_duplication_check.h world.h tunnel_optimization.h rrt_methods.h rrt_main_file.cpp rrt_methods.cpp ./MPNN/lib/libDNN.a ./ozcollide/libozcollide.a -o rrt -lm -g -std=c++0x

  
