
all:		
	g++ world.cpp obstacle.cpp support_methods.cpp path_duplication_check.cpp support_methods.h path_duplication_check.h world.h rrt_main_file.cpp ./rapid/libRAPID.a ./MPNN/lib/libDNN.a ./ozcollide/libozcollide.a -o rrt -lm -g `pkg-config --cflags --libs gtk+-3.0` -std=c++0x

  
